server:
  port: 7799

spring:
  application:
    name: reservation-gateway
  cloud:
    gateway:
      routes:
        - id: dingtalk_route
          uri: lb://reservation-service
          # 对应跟钉钉对接不需要验证的部分，现在同样是在手机端，与 /pro/v1/mobile/** 相同
          # uri: http://localhost:2005
          predicates:
            - Path=/reservations/**
            #- Path=/pro/v1/dingtalk/**
#          filters:
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 100
#                redis-rate-limiter.burstCapacity: 200
#                key-resolver: "#{@ipKeyResolver}"
        - id: mobile_route
          uri: lb://pro-web-dingtalk
          #        uri: http://localhost:2005
          predicates:
            - Path=/pro/v1/mobile/**
#          filters:
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 100
#                redis-rate-limiter.burstCapacity: 200
#                key-resolver: "#{@ipKeyResolver}"
      ## 默认过滤器，目前配置了熔断器
      default-filters:
  #        - name: Hystrix
  #          args:
  #            name: slowPaas
  #            fallbackUri: forward:/serviceFallback
  #    consul:
  #      host: 10.27.0.236
  #      enabled: true
  #      port: 8500
  #      discovery:
  #        health-check-interval: 15s
  ## 编码方式处理
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
## 默认日志等级
logging:
  level:
    root: info
    io.lettuce.core.protocol.RedisStateMachine: info
  path: /home/admin/logs